const data = {
    products:[
        {
          _id: '1',
          name: 'Nike Slim Shirt',
          category: 'Shirts',
          image: 'https://www.fillmurray.com/640/360',
          price: 120,
          brand: 'Nike',
          rating: 4.5,
          numReviews: 10,
          description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: 'https://www.fillmurray.com/640/360',
            price: 100,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          },
          {
            _id: '3',
            name: 'Lacoste Slim Shirt',
            category: 'Shirts',
            image: 'https://www.fillmurray.com/640/360',
            price: 220,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          },
          {
            _id: '4',
            name: 'Nike Pant',
            category: 'Pants',
            image: 'https://www.fillmurray.com/640/360',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          },
          {
            _id: '5',
            name: 'Puma Pant',
            category: 'Pants',
            image: 'https://www.fillmurray.com/640/360',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          },
          {
            _id: '1',
            name: 'Adidas Pant',
            category: 'Pants',
            image: 'https://www.fillmurray.com/640/360',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
          },
    ],
}

export default data;